package org.objkt.gl.wrapper;

import org.objkt.gl.enums.*;

public abstract class GLESWrapper extends Wrapper {

	public abstract void glAlphaFunc(int func, float ref);
	public abstract void glAlphaFuncx(int func, int ref);
	public abstract void glBlendBarrier();
	public abstract void glClearColorx(int red, int green, int blue, int alpha);
	public abstract void glClearDepthx(int depth);
	public abstract void glClientActiveTexture(int texture);
	public abstract void glClipPlanef(int p, long eqn);
	public abstract void glClipPlanex(int plane, long equation);
	public abstract void glColor4f(float red, float green, float blue, float alpha);
	public abstract void glColor4ub(byte red, byte green, byte blue, byte alpha);
	public abstract void glColor4x(int red, int green, int blue, int alpha);
	public abstract void glColorPointer(int size, int type, int stride, long pointer);
	public abstract void glDepthRangex(int n, int f);
	public abstract void glDisableClientState(int array);
	public abstract void glEnableClientState(int array);
	public abstract void glFogf(int pname, float param);
	public abstract void glFogfv(int pname, long params);
	public abstract void glFogx(int pname, int param);
	public abstract void glFogxv(int pname, long param);
	public abstract void glFrustumf(float l, float r, float b, float t, float n, float f);
	public abstract void glFrustumx(int l, int r, int b, int t, int n, int f);
	public abstract void glGetClipPlanef(int plane, long equation);
	public abstract void glGetClipPlanex(int plane, long equation);
	public abstract void glGetFixedv(int pname, long params);
	public abstract void glGetLightfv(int light, int pname, long params);
	public abstract void glGetLightxv(int light, int pname, long params);
	public abstract void glGetMaterialfv(int face, int pname, long params);
	public abstract void glGetMaterialxv(int face, int pname, long params);
	public abstract void glGetTexEnvfv(int target, int pname, long params);
	public abstract void glGetTexEnviv(int target, int pname, long params);
	public abstract void glGetTexEnvxv(int target, int pname, long params);
	public abstract void glGetTexParameterxv(int target, int pname, long params);
	public abstract void glLightModelf(int pname, float param);
	public abstract void glLightModelfv(int pname, long params);
	public abstract void glLightModelx(int pname, int param);
	public abstract void glLightModelxv(int pname, long param);
	public abstract void glLightf(int light, int pname, float param);
	public abstract void glLightfv(int light, int pname, long params);
	public abstract void glLightx(int light, int pname, int param);
	public abstract void glLightxv(int light, int pname, long params);
	public abstract void glLineWidthx(int width);
	public abstract void glLoadIdentity();
	public abstract void glLoadMatrixf(long m);
	public abstract void glLoadMatrixx(long m);
	public abstract void glMaterialf(int face, int pname, float param);
	public abstract void glMaterialfv(int face, int pname, long params);
	public abstract void glMaterialx(int face, int pname, int param);
	public abstract void glMaterialxv(int face, int pname, long param);
	public abstract void glMatrixMode(int mode);
	public abstract void glMultMatrixf(long m);
	public abstract void glMultMatrixx(long m);
	public abstract void glMultiTexCoord4f(int target, float s, float t, float r, float q);
	public abstract void glMultiTexCoord4x(int texture, int s, int t, int r, int q);
	public abstract void glNormal3f(float nx, float ny, float nz);
	public abstract void glNormal3x(int nx, int ny, int nz);
	public abstract void glNormalPointer(int type, int stride, long pointer);
	public abstract void glOrthof(float l, float r, float b, float t, float n, float f);
	public abstract void glOrthox(int l, int r, int b, int t, int n, int f);
	public abstract void glPointParameterx(int pname, int param);
	public abstract void glPointParameterxv(int pname, long params);
	public abstract void glPointSizex(int size);
	public abstract void glPolygonOffsetx(int factor, int units);
	public abstract void glPopMatrix();
	public abstract void glPrimitiveBoundingBox(float minX, float minY, float minZ, float minW, float maxX, float maxY, float maxZ, float maxW);
	public abstract void glPushMatrix();
	public abstract void glRotatef(float angle, float x, float y, float z);
	public abstract void glRotatex(int angle, int x, int y, int z);
	public abstract void glSampleCoveragex(int value, boolean invert);
	public abstract void glScalef(float x, float y, float z);
	public abstract void glScalex(int x, int y, int z);
	public abstract void glShadeModel(int mode);
	public abstract void glTexCoordPointer(int size, int type, int stride, long pointer);
	public abstract void glTexEnvf(int target, int pname, float param);
	public abstract void glTexEnvfv(int target, int pname, long params);
	public abstract void glTexEnvi(int target, int pname, int param);
	public abstract void glTexEnviv(int target, int pname, long params);
	public abstract void glTexEnvx(int target, int pname, int param);
	public abstract void glTexEnvxv(int target, int pname, long params);
	public abstract void glTexParameterx(int target, int pname, int param);
	public abstract void glTexParameterxv(int target, int pname, long params);
	public abstract void glTranslatef(float x, float y, float z);
	public abstract void glTranslatex(int x, int y, int z);
	public abstract void glVertexPointer(int size, int type, int stride, long pointer);}