package org.objct.gl.enums;

import java.util.*;

import org.objkt.gl.GLConstants;

public enum MemoryBarrierMask {
	ALL_BARRIER_BITS(GLConstants.GL_ALL_BARRIER_BITS),
	ATOMIC_COUNTER_BARRIER_BIT(GLConstants.GL_ATOMIC_COUNTER_BARRIER_BIT),
	BUFFER_UPDATE_BARRIER_BIT(GLConstants.GL_BUFFER_UPDATE_BARRIER_BIT),
	CLIENT_MAPPED_BUFFER_BARRIER_BIT(GLConstants.GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT),
	COMMAND_BARRIER_BIT(GLConstants.GL_COMMAND_BARRIER_BIT),
	ELEMENT_ARRAY_BARRIER_BIT(GLConstants.GL_ELEMENT_ARRAY_BARRIER_BIT),
	FRAMEBUFFER_BARRIER_BIT(GLConstants.GL_FRAMEBUFFER_BARRIER_BIT),
	PIXEL_BUFFER_BARRIER_BIT(GLConstants.GL_PIXEL_BUFFER_BARRIER_BIT),
	QUERY_BUFFER_BARRIER_BIT(GLConstants.GL_QUERY_BUFFER_BARRIER_BIT),
	SHADER_IMAGE_ACCESS_BARRIER_BIT(GLConstants.GL_SHADER_IMAGE_ACCESS_BARRIER_BIT),
	SHADER_STORAGE_BARRIER_BIT(GLConstants.GL_SHADER_STORAGE_BARRIER_BIT),
	TEXTURE_FETCH_BARRIER_BIT(GLConstants.GL_TEXTURE_FETCH_BARRIER_BIT),
	TEXTURE_UPDATE_BARRIER_BIT(GLConstants.GL_TEXTURE_UPDATE_BARRIER_BIT),
	TRANSFORM_FEEDBACK_BARRIER_BIT(GLConstants.GL_TRANSFORM_FEEDBACK_BARRIER_BIT),
	UNIFORM_BARRIER_BIT(GLConstants.GL_UNIFORM_BARRIER_BIT),
	VERTEX_ATTRIB_ARRAY_BARRIER_BIT(GLConstants.GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT),
	VERTEX_ATTRIB_ARRAY_BARRIER_BIT_EXT(GLConstants.GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT_EXT),
	ELEMENT_ARRAY_BARRIER_BIT_EXT(GLConstants.GL_ELEMENT_ARRAY_BARRIER_BIT_EXT),
	UNIFORM_BARRIER_BIT_EXT(GLConstants.GL_UNIFORM_BARRIER_BIT_EXT),
	TEXTURE_FETCH_BARRIER_BIT_EXT(GLConstants.GL_TEXTURE_FETCH_BARRIER_BIT_EXT),
	SHADER_GLOBAL_ACCESS_BARRIER_BIT_NV(GLConstants.GL_SHADER_GLOBAL_ACCESS_BARRIER_BIT_NV),
	SHADER_IMAGE_ACCESS_BARRIER_BIT_EXT(GLConstants.GL_SHADER_IMAGE_ACCESS_BARRIER_BIT_EXT),
	COMMAND_BARRIER_BIT_EXT(GLConstants.GL_COMMAND_BARRIER_BIT_EXT),
	PIXEL_BUFFER_BARRIER_BIT_EXT(GLConstants.GL_PIXEL_BUFFER_BARRIER_BIT_EXT),
	TEXTURE_UPDATE_BARRIER_BIT_EXT(GLConstants.GL_TEXTURE_UPDATE_BARRIER_BIT_EXT),
	BUFFER_UPDATE_BARRIER_BIT_EXT(GLConstants.GL_BUFFER_UPDATE_BARRIER_BIT_EXT),
	FRAMEBUFFER_BARRIER_BIT_EXT(GLConstants.GL_FRAMEBUFFER_BARRIER_BIT_EXT),
	TRANSFORM_FEEDBACK_BARRIER_BIT_EXT(GLConstants.GL_TRANSFORM_FEEDBACK_BARRIER_BIT_EXT),
	ATOMIC_COUNTER_BARRIER_BIT_EXT(GLConstants.GL_ATOMIC_COUNTER_BARRIER_BIT_EXT),
	CLIENT_MAPPED_BUFFER_BARRIER_BIT_EXT(GLConstants.GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT_EXT),
	ALL_BARRIER_BITS_EXT(GLConstants.GL_ALL_BARRIER_BITS_EXT);

	MemoryBarrierMask(int token) {
		this.token = token;
	}

	public final int token;

	public static final MemoryBarrierMask[] VALUES = values();
	private static Map<Integer, MemoryBarrierMask> getMap() {
		Map<Integer, MemoryBarrierMask> map = new HashMap<>();
		for(MemoryBarrierMask val : VALUES) map.put(val.token, val);
		return map;	}
	private static final Map<Integer, MemoryBarrierMask> MAP = Collections.unmodifiableMap(getMap());
	public static MemoryBarrierMask get(int raw) { return MAP.get(raw); }

	public static class Mask {
		static final ThreadLocal<Mask> MASKS = ThreadLocal.withInitial(() -> new Mask());
		int value;

		public static Mask of(MemoryBarrierMask... values) {
			Mask m = MASKS.get();
			m.value = 0;
			for(MemoryBarrierMask enm : values)
				m.value += enm.token;
			return m;
		}
		public int value() { return value; }	}
}